matrix:
  - name: ortografia
    sources:
      - content/*/index.mdgs
      # ignorar textos anteriores al 2009 - demasiados errores
      - content/20[1-9]*.md
    aspell:
      lang: es
      mode: markdown
      ignore-case: true
      ignore: 3
      d: es
    dictionary:
      wordlists:
      - es-local.dic
    default_encoding: utf-8
    pipeline:
    - pyspelling.filters.context:
        context_visible_first: true
        escapes: '\\[\\`~]'
        delimiters:
        # Ignore multiline content between fences (fences can have 3 or more plus)
        # +++
        # content
        # +++
        - open: '(?s)^(?P<open> *[\+\-]{3,})$'
          close: '^(?P=open)$'
        # Ignore text between inline pluses
        - open: '(?P<open>\++)'
          close: '(?P=open)'
        # Ignore text between inline {{ }}
        - open: '^\{\{'
          content: '.+'
          close: '\}\}$'
