name: revisar

on:
  pull_request:
    branches: [ main ]

jobs:
  revisar:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: v0.19.2
    steps:
      - name: Actualizar sistema
        run: |
          sudo apt-get update
          sudo apt-get install aspell aspell-es

      - name: Actualizar sistema a Español
        run: |
          sudo locale-gen es_MX.UTF-8
          sudo update-locale

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Actualizar Python
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install pyspelling pymarkdownlnt

      - name: Número de commits más 1 (merge commit)
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Extraer repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Obtener archivos markdown modificados
        id:  archivos-md-modificados
        env:
          BRANCH_MAIN: ${{ github.event.pull_request.base.sha }}
          BRANCH_TOPIC: ${{ github.event.pull_request.head.sha }}
        run: |
          {
            echo 'archivos_modificados<<EOF'
            git log --oneline --name-only ${BRANCH_MAIN}..${BRANCH_TOPIC} -- content/** | grep '\.md$' | sort | uniq
            echo EOF
          } >> "$GITHUB_OUTPUT"
          echo "numero_de_cambios=$(echo $ARCIHVOS_MODIFICADOS | wc -l)" >> "$GITHUB_OUTPUT"

      - name: Revisar formato markdown
        if: steps.archivos-md-modificados.outputs.numero_de_cambios != 0
        env:
          ARCHIVOS_MD_CAMBIADOS: ${{ steps.archivos-md-modificados.outputs.archivos_modificados }}
        run: |
          pymarkdown scan $ARCHIVOS_MD_CAMBIADOS

      - name: Revisar ortografia
        if: steps.archivos-md-modificados.outputs.numero_de_cambios != 0
        env:
          ARCHIVOS_MD_CAMBIADOS: ${{ steps.archivos-md-modificados.outputs.archivos_modificados }}
        run: |
          for ARCHIVO in ${ARCHIVOS_MD_CAMBIADOS}; do
            python -m pyspelling -n ortografia -S $ARCHIVO
          done

      - name: Descargar Zola
        run: |
          wget "https://github.com/getzola/zola/releases/download/${ZOLA_VERSION}/zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"

      - name: Instalar Zola
        run: |
          tar vxzf ./zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz

      - name: Construir sitio web
        run: |
          LANG=es_MX.UTF-8 ./zola build
