name: revisar

on:
  pull_request:
    branches: [ main ]

jobs:
  revisar:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: v0.18.0
    steps:
      - name: Actualizar sistema
        run: |
          sudo apt-get update
          sudo apt-get install aspell aspell-es

      - name: Actualizar sistema a Español
        run: |
          sudo locale-gen es_MX.UTF-8
          sudo update-locale

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Actualizar Python
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install pyspelling pymarkdownlnt

      - name: Extraer repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Obtener archivos markdown modificados
        id:  archivos-md-modificados
        uses: tj-actions/changed-files@v42
        with:
          files: |
            content/**.md

      - name: Revisar formato markdown
        if: steps.archivos-md-modificados.outputs.any_changed == 'true'
        env:
          ARCHIVOS_MD_CAMBIADOS: ${{ steps.archivos-md-modificados.outputs.all_changed_files }}
        run: |
          pymarkdown -d MD041 scan $ARCHIVOS_MD_CAMBIADOS

      - name: Revisar ortografia
        if: steps.archivos-md-modificados.outputs.any_changed == 'true'
        env:
          ARCHIVOS_MD_CAMBIADOS: ${{ steps.archivos-md-modificados.outputs.all_changed_files }}
        run: |
          python -m pyspelling -n ortografia -S $ARCHIVOS_MD_CAMBIADOS

      - name: Descargar Zola
        run: |
          wget "https://github.com/getzola/zola/releases/download/${ZOLA_VERSION}/zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz"

      - name: Instalar Zola
        run: |
          tar vxzf ./zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz

      - name: Construir sitio web
        run: |
          LANG=es_MX.UTF-8 ./zola build
