name: revisar

on:
  pull_request:
    branches: [main]

jobs:
  revisar:
    runs-on: ubuntu-latest

    steps:
      - name: Extraer repositorio
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Configurar entorno
        uses: ./.github/actions/setup
        with:
          setup-python: true
          setup-zola: true
          setup-locale: true
          install-system-packages: 'aspell aspell-es'

      - name: Revisar calidad de código Python
        run: |
          uv run ruff check scripts/
          uv run pylint scripts/

      - name: Obtener archivos markdown modificados
        id: archivos-md-modificados
        uses: tj-actions/changed-files@v47
        with:
          files: |
            content/**.md
            content/**/**.md

      - name: Revisar formato markdown
        if: steps.archivos-md-modificados.outputs.any_changed == 'true'
        env:
          ARCHIVOS_MD_CAMBIADOS: ${{ steps.archivos-md-modificados.outputs.all_changed_files }}
        run: |
          uv run pymarkdown scan $ARCHIVOS_MD_CAMBIADOS

      - name: Revisar ortografía
        if: steps.archivos-md-modificados.outputs.any_changed == 'true'
        env:
          ARCHIVOS_MD_CAMBIADOS: ${{ steps.archivos-md-modificados.outputs.all_changed_files }}
        run: |
          for ARCHIVO in ${ARCHIVOS_MD_CAMBIADOS}; do
            uv run pyspelling -n ortografia -S $ARCHIVO
          done

      - name: Construir sitio web
        run: |
          LANG=es_MX.UTF-8 ./zola build
